Support for Django >=4.2
dduong42/s3manifestcollectstatic pull request #2
Opened 2023-05-31 10:17 UTC by fellu

2023-05-31 11:05 UTC, Tupeco requested changes
STORAGES is not yet mandatory in Django 4.2 (just mutually exclusive with the old STATICFILES_STORAGE) so these might be better served with some getattrs.

2023-05-31 11:05 UTC, Tupeco commented on s3manifestcollectstatic/management/commands/s3manifestcollectstatic.py
> +            if VERSION[0] >= 4 and VERSION[1] >= 2:
`STORAGES` is not yet mandatory in Django 4.2 (just mutually exclusive with the old `STATICFILES_STORAGE`) so these might be better served with some getattrs.

2023-06-05 19:58 UTC, closed without merging

2023-06-05 20:03 UTC, dduong42 commented
Thank you @fellu and @Tupeco. I've changed this commit a little bit and released a new version.

2023-06-08 21:36 UTC, fellu commented
> Thank you @fellu and @Tupeco. I've changed this commit a little bit and released a new version.

thanks! And also in general thanks for keeping this alive, pretty crazy that this kind of functionality is not part of any storage solution :F